grosenberger/easypqp

.gitignore
easypqp/convert.py
easypqp/library.py
easypqp/main.py

This PR adds support for IM and Philosopher results.

[FEATURE] Support for IM and Philosopher results

---

easypqp/library.py

plot true alignment regression
prevent overwriting of RT alignment plots

some alignment plot fixes.

---

easypqp/main.py

I think that is a typo. `rt_lowess_fraction` has a default of `0.05`

change default for `im_lowess_fraction`

---

easypqp/convert.py

Hi,
I ran into a decoding problem when running easypqp inside a docker container.
Adding the AttributeError exception seems to fix the problem for me.
Would be great to have this one more time merged and released to use it inside the container environment.
Best,
Leon

Fix decoding problem

---

easypqp/convert.py

I realized that introducing these scores is not necessary and makes it dependent on using the search engine comet.
Would be better to have it removed to keep it more flexible, I suppose.

rm comet specific scores

---

easypqp/library.py

Previous code checks for columns in the string im_reference. Changed for checking of these columns in the corresponding pandas dataframe file.
I'm new to git contributing so I apologize if I'm not doing this correctly :) .

Bug in im reference file error checking

---

setup.py

Fix https://github.com/Nesvilab/FragPipe/issues/304

Set a minimum version for `pandas`

---

setup.py

Set minimum version for `pyOpenMS`

Set minimum version for `pyOpenMS`

---

easypqp/library.py
easypqp/main.py

if reference RT file is not provided, write reference run RT tsv file

write reference run RT tsv file

---

easypqp/convert.py

Bug reported in: Nesvilab/FragPipe/issues/370

[FIX] fc3c4a59c2bf36dfb295851de109bb12b0c88293

---

easypqp/library.py
easypqp/main.py

Same as 53b149e013061fa2b349463d55cd0c901cacaed3, but for IM.

write reference run IM tsv file

---

MANIFEST.in

include unimod.xml in sdist

---

easypqp/library.py

https://github.com/joblib/loky/issues/192

workaround `loky` issue

---

easypqp/library.py
easypqp/main.py

add boolean parameters "--perform_rt_calibration" and "--perform_im_calibration" to library command which optionally disable RT/IM calibration. 
I know that this might not lead to desirable behaviour (and makes the program more complex by adding more parameters), however I think this is useful for testing purposes or if calibration is to be done manually. 
Note: most of the edits are just indentation, I don't know why git makes it seem like a lot of lines are being added/deleted

[FEATURE] optional calibration

---

easypqp/convert.py
easypqp/test_convert.py

https://github.com/Nesvilab/FragPipe/issues/880

Fix a scan number extraction bug for the non-Thermo vendors.

---

easypqp/convert.py
easypqp/library.py

Modify the neutral loss ions to make it compatible with DIA-NN

---

easypqp/data/unimod.xml

There are several modifications, including TMTpro missing in the old unimod file.
Thanks,
Fengchao

Update the unimod.xml to the latest version.

---

easypqp/convert.py

Reported by https://github.com/Nesvilab/FragPipe/issues/1275

Fix another bug due to 0 IDs in the pepxml file.

---

easypqp/library.py

This feature generates a union set of protein identifiers for each peptide in case individual runs provide different sets. This function is only used without FragPipe filter lists, as there the workflow already provides global protein grouping.

[FEATURE] Generate canonical set of protein identifiers

---

easypqp/convert.py
easypqp/main.py

Related to #112
@fcyu are you up for supporting this again? :) I would definitely keep an eye on the idxml-part of this repo if you would.
Tested with idXML `easypqp convert` and `easypqp library` locally worked fine.

Fix idxml parsing

---

easypqp/convert.py

fix https://github.com/Nesvilab/FragPipe/issues/2432

fix https://github.com/Nesvilab/FragPipe/issues/2432
